export const RUN_LIST_REQUEST = "RUN_LIST_REQUEST";
export const RUN_LIST_FAIL = "RUN_LIST_FAIL";
export const RUN_LIST_SUCCESS = "RUN_LIST_SUCCESS";

export const RUN_DETAILS_REQUEST = "RUN_DETAILS_REQUEST";
export const RUN_DETAILS_SUCCESS = "RUN_DETAILS_SUCCESS";
export const RUN_DETAILS_FAIL = "RUN_DETAILS_FAIL";
export const RUN_DETAILS_RESET = "RUN_DETAILS_RESET";

export const RUN_DELETE_REQUEST = "RUN_DELETE_REQUEST";
export const RUN_DELETE_SUCCESS = "RUN_DELETE_SUCCESS";
export const RUN_DELETE_FAIL = "RUN_DELETE_FAIL";

export const RUN_CREATE_REQUEST = "RUN_CREATE_REQUEST";
export const RUN_CREATE_SUCCESS = "RUN_CREATE_SUCCESS";
export const RUN_CREATE_FAIL = "RUN_CREATE_FAIL";
export const RUN_CREATE_RESET = "RUN_CREATE_RESET";

export const RUN_UPDATE_REQUEST = "RUN_UPDATE_REQUEST";
export const RUN_UPDATE_SUCCESS = "RUN_UPDATE_SUCCESS";
export const RUN_UPDATE_FAIL = "RUN_UPDATE_FAIL";
export const RUN_UPDATE_RESET = "RUN_UPDATE_RESET";
